name: AI PR Review

on:
  # open時だけに設定し、一次レビューとして利用する
  pull_request:
    types: [opened, reopened]

permissions:
  issues: write
  pull-requests: write

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run AI PR Review on opened pull request
    env:
      COMMON_INSTRUCTIONS: >-
        日本語で回答してください。
        以下の原則に従ってコメントしてください。
        ロジック上の問題がないかを確認する。
        変数や関数名が冗長なのは避けてください。
        コード品質に問題がないことを確認する.
        pythonもしくはjavascriptのコーディング規約に違反した記述はやめる。
        pydocなどの適切なコメントが関数に記述されているようにする.
        既存実装に影響を与え、バグやエラーとなる懸念点を探す.
        セキュリティに脆弱性をもたらすようなコードがないかを探す.
        さらによりよい方向へ改善できる部分がないか探す.
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          GITHUB_ACTION.AUTO_REVIEW: true
          GITHUB_ACTION.AUTO_DESCRIBE: false
          GITHUB_ACTION.AUTO_IMPROVE: true
          PR_REVIEWER.EXTRA_INSTRUCTIONS: ${{ env.COMMON_INSTRUCTIONS }}
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: ${{ env.COMMON_INSTRUCTIONS }}
          PR_CODE_SUGGESTIONS.NUM_CODE_SUGGESTIONS: 5
          CONFIG.MODEL: gpt-4o
